TASK 5 PR
ZaniInc/FifthTaskZanozin pull request #1
Opened 2022-07-24 17:09 UTC by ZaniInc

2022-07-28 17:20 UTC, BhHaipls requested changes

2022-07-28 17:20 UTC, BhHaipls commented on contracts/MyNFT.sol
> +import "hardhat/console.sol";
unused import

2022-07-28 17:20 UTC, BhHaipls commented on contracts/MyNFT.sol
> +// SPDX-License-Identifier: UNLICENSED
default license is MIT/ISC

2022-07-28 17:20 UTC, BhHaipls commented on contracts/MyNFT.sol
> +// SPDX-License-Identifier: UNLICENSED
for sc

2022-07-28 17:20 UTC, BhHaipls commented on contracts/MyNFT.sol
> +contract MyNFT is ERC721, Ownable {
interface for your NFT is miss

2022-07-28 17:20 UTC, BhHaipls commented on contracts/MyNFT.sol
> +    event SetBaseURI(string baseURILink_);
param for event should be without _ in end of name

2022-07-28 17:20 UTC, BhHaipls commented on contracts/MyNFT.sol
> +    event Buy(address buyer, uint256 ethers);
should add id of nft which was mint for buyer

2022-07-28 17:20 UTC, BhHaipls commented on contracts/MyNFT.sol
> +            tokenCountId._value < tokenSupply,
use current() method from Counter instead of _value.

2022-07-28 17:20 UTC, BhHaipls commented on contracts/MyNFT.sol
> +        _safeMint(msg.sender, tokenCountId.current());
in this case, nft will start from 1 id. should start from zero

2022-07-28 17:20 UTC, BhHaipls commented on contracts/MyNFT.sol
> +    function setBaseURI(string memory baseURI_) public onlyOwner {
should be internal

2022-07-28 17:20 UTC, BhHaipls commented on contracts/MyNFT.sol
> +            bytes(baseURI).length > 0
it's not need check, because baseURI always will have length more then 0

2022-07-28 17:20 UTC, BhHaipls commented on contracts/MyNFT.sol
> +    function setBaseURI(string memory baseURI_) public onlyOwner {
and call only from constructor

2022-07-28 17:20 UTC, BhHaipls commented on scripts/deploy.js
> +
it's script file should be change/delete it's not from this task

2022-07-29 20:57 UTC, BhHaipls requested changes

2022-07-29 20:57 UTC, BhHaipls commented on contracts/MyNFT.sol
> +contract MyNFT is ERC721, Ownable, IMyNFT {
interfaces have priority, in order in extends list

2022-07-29 20:57 UTC, BhHaipls commented on contracts/MyNFT.sol
> +            tokenCountId.current() <= tokenSupply,
for gas optimization create variable for tokenCountId.current() for interact with memory and not interact with storage every time

2022-07-29 20:57 UTC, BhHaipls commented on contracts/MyNFT.sol
> +    function setBaseURI(string memory baseURI_) internal onlyOwner {
internal function name should start with "_"

2022-07-29 20:57 UTC, BhHaipls commented on contracts/MyNFT.sol
> +        return string(abi.encodePacked(baseURI, tokenId.toString(), ".json"));
just use direct call _baseURI() instead create memory variable

2022-07-29 20:57 UTC, BhHaipls commented on contracts/interfaces/IMyNFT.sol
> +     * @param ethers - how many ether's transfer
tokenId is miss in param list in documentation

2022-07-29 20:57 UTC, BhHaipls commented on contracts/MyNFT.sol
> +        tokenCountId.increment();
increment operation should be before emit event
follow next operation ordering:
1) require
2) calculation
4) change storage
5) transfers
6) event

it's by default, but you can change ordering if needed but not in this case

2022-07-29 20:57 UTC, BhHaipls commented on test/MyNFT.test.js
> +  describe("Initialize contract - false", async () => {
add tests for you check the parameters initialize is corectly

2022-07-29 20:57 UTC, BhHaipls commented on test/MyNFT.test.js
> +  describe("Initialize contract - false", async () => {
price, baseURI, maxTotalSupply etc

2022-07-29 20:57 UTC, BhHaipls commented on contracts/MyNFT.sol
> +    uint256 public tokenSupply = 5;
you never change this variable, should be constant

2022-07-29 20:57 UTC, BhHaipls commented on contracts/MyNFT.sol
> +    string public baseURILink;
should be immutable type

2022-07-29 20:57 UTC, BhHaipls commented on test/MyNFT.test.js
> +    describe("False", async () => {
false it's not corectly name for describe with fail tests
rename to: "Should fail if..."

2022-07-29 20:57 UTC, BhHaipls commented on test/MyNFT.test.js
> +  describe("setNftPrice function", async () => {
just setNftPrice without function suffix in name

2022-07-29 20:57 UTC, BhHaipls commented on test/MyNFT.test.js
> +      it("Ownable: caller is not the owner", async () => {
call is not owner

2022-07-29 20:57 UTC, BhHaipls commented on test/MyNFT.test.js
> +    describe("Done", async () => {
Success...

2022-07-29 20:57 UTC, BhHaipls commented on test/MyNFT.test.js
> +      it("change price by owner", async () => {
change price by owner and emit events

2022-07-29 20:57 UTC, BhHaipls commented on test/MyNFT.test.js
> +        expect(tokenURI).to.be.equal("https://gateway.pinata.cloud/ipfs/QmcUH66aaS6iCLJdDCas845xkzcRYgq8NNwfs3FMir8wTs/0.json");
you should check tokenURI in another specific tests

2022-07-29 20:57 UTC, BhHaipls commented on test/MyNFT.test.js
> +    describe("False", async () => {
Should fail if

2022-07-29 20:57 UTC, BhHaipls commented on test/MyNFT.test.js
> +      it("Error : payment value too low", async () => {
or big, and add check if user send more funds, should fail also

2022-07-29 22:10 UTC, BhHaipls requested changes

2022-07-29 22:10 UTC, BhHaipls commented on contracts/MyNFT.sol
> +
after sell , some eth will lock on contract, should add method for get paids user eth. Can be callo nly from Owner

2022-08-04 21:58 UTC, BeeTeo approved these changes

2022-08-04 22:06 UTC, BhHaipls approved these changes

2022-08-04 22:26 UTC, BhHaipls approved these changes
Approved

2022-08-04 22:26 UTC, BhHaipls requested changes
should change name of tests

2022-08-04 22:27 UTC, BhHaipls approved these changes
not need, completed, approved

2022-08-05 13:02 UTC, merged